apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  labels:
    app: app1
    tier: backend
spec:
  selector:
    matchLabels:
      app: app1
      tier: backend
  template:
    metadata:
      labels:
        app: app1
        tier: backend
    spec:
      containers:
        - name: app1
          image: app1:latest
          imagePullPolicy: IfNotPresent
          securityContext:
            readOnlyRootFilesystem: true
          ports:
            - name: http-port
              containerPort: 8000
          